export default [
  { title: "Feliz", character: "😊" },
  { title: "Sorrindo 1", character: "🙂" },
  { title: "Sorrindo 2", character: "😀" },
  { title: "Sorrindo 3", character: "😁" },
  { title: "Sorrindo 4", character: "😊" },
  { title: "Rindo", character: "😂" },
  { title: "Abraçando", character: " 🤗" },
  { title: "Piscando", character: "😉" },
  { title: "Óculos", character: "😎" },
  { title: "Apaixonado", character: "😍" },
  { title: "Carinhoso", character: "🥰" },
  { title: "Beijo", character: "😘" },
  { title: "Festejando", character: "🥳" },
  { title: "Surpreso", character: "😮" },
  { title: "Triste", character: "🙁" },
  { title: "Bravo", character: "😠" },
  { title: "Coração", character: "❤️" },
  { title: "Notebook", character: "💻" },
  { title: "Beleza", character: "👍" },
  { title: "Aplausos", character: "👏" },
  { title: "Apreciar", character: "🙏" },
  { title: "Festejar", character: "🎉" },
  { title: "Dançando 1", character: "💃" },
  { title: "Dançando 2", character: "🕺" },
];
